-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  crypto_algorithms

CREATE TABLE IF NOT EXISTS crypto_algorithms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class TEXT NOT NULL,                       -- 'kem' | 'sig' | 'hash' | 'symmetric'
  name  VARCHAR(120) NOT NULL,               -- e.g. 'ML-KEM-768','ML-DSA-2','SHA3-512','AES-256-GCM'
  variant VARCHAR(80) NULL,                  -- e.g. 'hybrid-x25519', 'fips-202'
  variant_norm TEXT GENERATED ALWAYS AS (COALESCE(variant,'')) STORED,
  nist_level SMALLINT NULL,                  -- 1..5 for PQC, NULL for others
  status TEXT NOT NULL DEFAULT 'active',     -- 'active' | 'deprecated' | 'experimental'
  params JSONB NULL,                         -- e.g. { "ct_max_len": 1792, "pubkey_len": 1184 }
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_crypto_algorithms UNIQUE (class, name, variant_norm),
  CONSTRAINT uq_crypto_algorithms_raw UNIQUE (class, name, variant),
  CONSTRAINT chk_ca_class CHECK (class IN ('kem','sig','hash','symmetric')),
  CONSTRAINT chk_ca_status CHECK (status IN ('active','deprecated','experimental'))
);
